-- ==============================
-- SEED 160 INSPECTION ITEMS
-- ==============================

INSERT INTO inspection_items (category, name, description, display_order) VALUES
-- ENGINE (1-15)
('Engine', 'Engine Start', 'Mesin dapat menyala dengan mudah', 1),
('Engine', 'Engine Idle', 'Putaran mesin stabil saat idle', 2),
('Engine', 'Engine Noise', 'Tidak ada suara berisik abnormal', 3),
('Engine', 'Engine Oil Level', 'Level oli mesin normal', 4),
('Engine', 'Engine Oil Leak', 'Tidak ada kebocoran oli mesin', 5),
('Engine', 'Radiator Condition', 'Kondisi radiator baik', 6),
('Engine', 'Radiator Coolant Level', 'Level coolant radiator normal', 7),
('Engine', 'Cooling Fan', 'Kipas pendingin berfungsi', 8),
('Engine', 'Drive Belt', 'V-belt/serpentine belt kondisi baik', 9),
('Engine', 'Battery Condition', 'Aki dalam kondisi baik', 10),
('Engine', 'Air Filter', 'Filter udara bersih', 11),
('Engine', 'Fuel Pump', 'Pompa bensin berfungsi normal', 12),
('Engine', 'Spark Plug', 'Busi dalam kondisi baik', 13),
('Engine', 'Engine Mounting', 'Engine mounting tidak rusak', 14),
('Engine', 'Turbo Condition', 'Turbo berfungsi normal (jika ada)', 15),

-- TRANSMISSION (16-25)
('Transmission', 'Transmission Shift', 'Perpindahan gigi halus', 16),
('Transmission', 'Transmission Oil', 'Level oli transmisi normal', 17),
('Transmission', 'Clutch Condition', 'Kopling tidak slip (manual)', 18),
('Transmission', 'Gearbox Noise', 'Tidak ada suara abnormal pada gearbox', 19),
('Transmission', 'Drive Shaft', 'Drive shaft kondisi baik', 20),
('Transmission', 'Differential', 'Differential berfungsi normal', 21),
('Transmission', 'CV Joint', 'CV Joint tidak berbunyi', 22),
('Transmission', 'Transmission Mount', 'Transmission mounting kondisi baik', 23),
('Transmission', 'Propeller Shaft', 'Propeller shaft kondisi baik (4WD)', 24),
('Transmission', 'Transmission Leak', 'Tidak ada kebocoran transmisi', 25),

-- BRAKE (26-35)
('Brake', 'Brake Pad', 'Kampas rem masih tebal', 26),
('Brake', 'Brake Disc', 'Disc brake tidak aus', 27),
('Brake', 'Brake Fluid', 'Level minyak rem normal', 28),
('Brake', 'Brake Hose', 'Selang rem tidak bocor', 29),
('Brake', 'Brake Caliper', 'Caliper rem berfungsi normal', 30),
('Brake', 'ABS System', 'Sistem ABS berfungsi', 31),
('Brake', 'Hand Brake', 'Rem tangan berfungsi baik', 32),
('Brake', 'Brake Booster', 'Brake booster berfungsi', 33),
('Brake', 'Brake Master Cylinder', 'Master cylinder rem baik', 34),
('Brake', 'Brake Performance', 'Performa pengereman optimal', 35),

-- SUSPENSION (36-45)
('Suspension', 'Front Shock Absorber', 'Shock absorber depan berfungsi', 36),
('Suspension', 'Rear Shock Absorber', 'Shock absorber belakang berfungsi', 37),
('Suspension', 'Spring Condition', 'Per kondisi baik', 38),
('Suspension', 'Lower Arm', 'Lower arm tidak rusak', 39),
('Suspension', 'Ball Joint', 'Ball joint tidak longgar', 40),
('Suspension', 'Stabilizer Link', 'Stabilizer link kondisi baik', 41),
('Suspension', 'Suspension Bushings', 'Bushings suspensi tidak aus', 42),
('Suspension', 'Suspension Noise', 'Tidak ada suara abnormal suspensi', 43),
('Suspension', 'Wheel Bearing', 'Wheel bearing kondisi baik', 44),
('Suspension', 'Alignment', 'Wheel alignment sesuai', 45),

-- STEERING (46-50)
('Steering', 'Steering Wheel', 'Setir tidak bergetar', 46),
('Steering', 'Steering Rack', 'Steering rack kondisi baik', 47),
('Steering', 'Power Steering Pump', 'Pompa power steering berfungsi', 48),
('Steering', 'Steering Fluid', 'Level oli power steering normal', 49),
('Steering', 'Steering Column', 'Steering column tidak longgar', 50),

-- EXTERIOR (51-65)
('Exterior', 'Front Bumper', 'Bumper depan kondisi baik', 51),
('Exterior', 'Rear Bumper', 'Bumper belakang kondisi baik', 52),
('Exterior', 'Hood', 'Kap mesin tidak penyok', 53),
('Exterior', 'Front Left Door', 'Pintu depan kiri kondisi baik', 54),
('Exterior', 'Front Right Door', 'Pintu depan kanan kondisi baik', 55),
('Exterior', 'Rear Left Door', 'Pintu belakang kiri kondisi baik', 56),
('Exterior', 'Rear Right Door', 'Pintu belakang kanan kondisi baik', 57),
('Exterior', 'Roof', 'Atap tidak penyok', 58),
('Exterior', 'Front Fender', 'Fender depan kondisi baik', 59),
('Exterior', 'Rear Fender', 'Fender belakang kondisi baik', 60),
('Exterior', 'Paint Condition', 'Cat tidak pudar', 61),
('Exterior', 'Rust Check', 'Tidak ada karat berat', 62),
('Exterior', 'Windshield', 'Kaca depan tidak retak', 63),
('Exterior', 'Rear Glass', 'Kaca belakang kondisi baik', 64),
('Exterior', 'Side Mirrors', 'Spion kondisi baik', 65),

-- INTERIOR (66-75)
('Interior', 'Dashboard', 'Dashboard tidak retak', 66),
('Interior', 'Steering Condition', 'Kulit setir tidak aus', 67),
('Interior', 'Seat Condition', 'Jok tidak robek', 68),
('Interior', 'Seat Belt', 'Sabuk pengaman berfungsi', 69),
('Interior', 'Interior Trim', 'Trim interior lengkap', 70),
('Interior', 'Carpet Condition', 'Karpet bersih tidak lembab', 71),
('Interior', 'Door Trim', 'Trim pintu kondisi baik', 72),
('Interior', 'AC Cooling', 'AC dingin', 73),
('Interior', 'AC Blower', 'Blower AC berfungsi', 74),
('Interior', 'AC Filter', 'Filter AC bersih', 75),

-- ELECTRICAL (76-85)
('Electrical', 'Headlight', 'Lampu depan menyala', 76),
('Electrical', 'Tail Light', 'Lampu belakang menyala', 77),
('Electrical', 'Turn Signal', 'Lampu sein berfungsi', 78),
('Electrical', 'Fog Lamp', 'Lampu kabut berfungsi (jika ada)', 79),
('Electrical', 'Hazard Light', 'Lampu hazard berfungsi', 80),
('Electrical', 'Power Window', 'Power window berfungsi semua', 81),
('Electrical', 'Central Lock', 'Central lock berfungsi', 82),
('Electrical', 'Horn', 'Klakson berbunyi', 83),
('Electrical', 'Wiper Motor', 'Wiper berfungsi', 84),
('Electrical', 'Rear Defogger', 'Rear defogger berfungsi', 85),

-- SAFETY (86-90)
('Safety', 'Airbag System', 'Sistem airbag aktif', 86),
('Safety', 'ABS Warning', 'Tidak ada warning ABS', 87),
('Safety', 'Seat Belt Lock', 'Pengunci sabuk berfungsi', 88),
('Safety', 'Parking Sensor', 'Parking sensor berfungsi (jika ada)', 89),
('Safety', 'Rear Camera', 'Kamera belakang berfungsi (jika ada)', 90),

-- WHEELS (91-96)
('Wheels', 'Front Tire', 'Ban depan masih bagus', 91),
('Wheels', 'Rear Tire', 'Ban belakang masih bagus', 92),
('Wheels', 'Spare Tire', 'Ban cadangan ada', 93),
('Wheels', 'Wheel Rim', 'Velg tidak bengkok', 94),
('Wheels', 'Wheel Alignment', 'Spoor/stuur sesuai', 95),
('Wheels', 'Wheel Balance', 'Balance roda baik', 96),

-- UNDERBODY (97-100)
('Underbody', 'Chassis Frame', 'Chassis tidak rusak', 97),
('Underbody', 'Exhaust Pipe', 'Knalpot tidak bocor', 98),
('Underbody', 'Fuel Tank', 'Tangki bensin tidak bocor', 99),
('Underbody', 'Underbody Rust', 'Underbody bebas karat berat', 100),

-- BODY STRUCTURE (101-105)
('Body', 'Front Frame', 'Frame depan tidak penyok', 101),
('Body', 'Rear Frame', 'Frame belakang baik', 102),
('Body', 'Side Frame', 'Frame samping tidak rusak', 103),
('Body', 'Impact Damage', 'Tidak ada bekas tabrakan berat', 104),
('Body', 'Structural Weld', 'Tidak ada las bekas kecelakaan', 105),

-- ADDITIONAL (106-160)
('Additional', 'Key Condition', 'Kunci kondisi baik', 106),
('Additional', 'Remote Key', 'Remote kunci berfungsi (jika ada)', 107),
('Additional', 'Infotainment System', 'Head unit berfungsi', 108),
('Additional', 'Navigation System', 'Navigasi berfungsi (jika ada)', 109),
('Additional', 'USB Port', 'Port USB berfungsi', 110),
('Additional', 'Bluetooth', 'Bluetooth terkoneksi', 111),
('Additional', 'Speaker', 'Semua speaker berfungsi', 112),
('Additional', 'Sunroof', 'Sunroof berfungsi (jika ada)', 113),
('Additional', 'Cruise Control', 'Cruise control berfungsi (jika ada)', 114),
('Additional', 'Driver Assist', 'Driver assist berfungsi (jika ada)', 115),
('Additional', 'Lane Assist', 'Lane assist aktif (jika ada)', 116),
('Additional', 'Adaptive Cruise', 'Adaptive cruise berfungsi (jika ada)', 117),
('Additional', 'Auto Brake', 'Auto brake berfungsi (jika ada)', 118),
('Additional', 'Parking Brake', 'Parking brake elektrik berfungsi (jika ada)', 119),
('Additional', 'Interior Light', 'Lampu kabin berfungsi', 120),
('Additional', 'Door Lock', 'Kunci pintu berfungsi semua', 121),
('Additional', 'Seat Adjuster', 'Pengatur jok berfungsi', 122),
('Additional', 'Seat Heater', 'Heater jok berfungsi (jika ada)', 123),
('Additional', 'Seat Ventilation', 'Ventilasi jok berfungsi (jika ada)', 124),
('Additional', 'Rear Seat Condition', 'Jok belakang kondisi baik', 125),
('Additional', 'Third Row Seat', 'Jok baris ketiga (jika ada)', 126),
('Additional', 'Roof Rack', 'Roof rack kondisi baik (jika ada)', 127),
('Additional', 'Tow Hook', 'Tow hook tersedia', 128),
('Additional', 'Fuel Cap', 'Tutup bensin ada', 129),
('Additional', 'Trunk Lock', 'Kunci bagasi berfungsi', 130),
('Additional', 'Trunk Carpet', 'Karpet bagasi ada', 131),
('Additional', 'Spare Tools', 'Alat-alat cadangan lengkap', 132),
('Additional', 'Jack Tools', 'Dongkrak tersedia', 133),
('Additional', 'Owner Manual', 'Buku manual ada', 134),
('Additional', 'Service Book', 'Buku service ada', 135),
('Additional', 'Emission Test', 'Emisi sesuai standar', 136),
('Additional', 'OBD Scan', 'Tidak ada error code', 137),
('Additional', 'Battery Voltage', 'Tegangan aki normal (12.6V)', 138),
('Additional', 'Engine Compression', 'Kompresi mesin baik', 139),
('Additional', 'Engine Smoke', 'Tidak ada asap berlebih', 140),
('Additional', 'Fuel Consumption', 'Konsumsi BBM normal', 141),
('Additional', 'Acceleration Test', 'Akselerasi responsif', 142),
('Additional', 'Braking Distance', 'Jarak pengereman normal', 143),
('Additional', 'Steering Response', 'Respon setir presisi', 144),
('Additional', 'Suspension Comfort', 'Suspensi nyaman', 145),
('Additional', 'Noise Level', 'Suara mesin halus', 146),
('Additional', 'Vibration Level', 'Getaran minimal', 147),
('Additional', 'Interior Smell', 'Tidak ada bau apek', 148),
('Additional', 'Water Leak', 'Tidak ada kebocoran air', 149),
('Additional', 'Electrical Error', 'Tidak ada error listrik', 150),
('Additional', 'Sensor Check', 'Semua sensor aktif', 151),
('Additional', 'ECU Error', 'Tidak ada error ECU', 152),
('Additional', 'Cooling System', 'Sistem pendingin optimal', 153),
('Additional', 'Heater System', 'Heater berfungsi', 154),
('Additional', 'Parking Brake Hold', 'Parking brake hold berfungsi', 155),
('Additional', 'Wheel Torque', 'Torsi roda sesuai', 156),
('Additional', 'Wheel Nut', 'Mur roda lengkap', 157),
('Additional', 'Fuel Injector', 'Injector bersih', 158),
('Additional', 'Throttle Body', 'Throttle body bersih', 159),
('Additional', 'Final Inspection', 'Inspeksi final selesai', 160);
