import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query Health {\n    health\n  }\n": typeof types.HealthDocument,
    "\n  query Me {\n    me {\n      id\n      name\n      email\n      phone\n      avatar\n      role\n      isVerified\n      settings { id userId key value }\n      tokenBalance\n    }\n  }\n": typeof types.MeDocument,
    "\n  query Listings($page: Int, $perPage: Int, $filter: ListingFilter) {\n    listings(page: $page, perPage: $perPage, filter: $filter) {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      isFeatured\n      condition\n      brand { id name slug logo }\n      model { id name slug }\n      transmission\n      fuelType\n      color\n      bodyType\n      seller { id name avatar isVerified rating totalReviews }\n      viewCount\n      createdAt\n    }\n  }\n": typeof types.ListingsDocument,
    "\n  query Listing($id: ID!) {\n    listing(id: $id) {\n      id\n      slug\n      title\n      description\n      price\n      year\n      mileage\n      city\n      province\n      images\n      isFeatured\n      isNegotiable\n      condition\n      brand { id name slug logo }\n      model { id name slug }\n      variant\n      transmission\n      fuelType\n      color\n      bodyType\n      engineCapacity\n      seatCapacity\n      features\n      category { id name slug }\n      inspection {\n        id\n        status\n        overallScore\n        inspectedAt\n        reportUrl\n        categories { id name score items { id name status notes } }\n      }\n      seller { id name avatar phone email isVerified rating totalReviews joinedAt totalListings address province city }\n      reviewCount\n      viewCount\n      favorites\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.ListingDocument,
    "\n  query ListingBySlug($slug: String!) {\n    listingBySlug(slug: $slug) {\n      id\n      slug\n      title\n      description\n      price\n      year\n      mileage\n      city\n      province\n      images\n      isFeatured\n      isNegotiable\n      condition\n      brand { id name slug logo }\n      model { id name slug }\n      variant\n      transmission\n      fuelType\n      color\n      bodyType\n      engineCapacity\n      seatCapacity\n      features\n      category { id name slug }\n      inspection {\n        id\n        status\n        overallScore\n        inspectedAt\n        reportUrl\n        categories { id name score items { id name status notes } }\n      }\n      seller { id name avatar phone email isVerified rating totalReviews joinedAt totalListings address province city }\n      reviewCount\n      viewCount\n      favorites\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.ListingBySlugDocument,
    "\n  query MyListings($page: Int, $perPage: Int) {\n    myListings(page: $page, perPage: $perPage) {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      status\n      viewCount\n      favorites\n      isFeatured\n      condition\n      brand { id name slug }\n      model { id name slug }\n      transmission\n      fuelType\n      createdAt\n    }\n  }\n": typeof types.MyListingsDocument,
    "\n  query Brands {\n    brands {\n      id\n      name\n      slug\n      logo\n      logoUrl\n      country\n      models { id name slug }\n    }\n  }\n": typeof types.BrandsDocument,
    "\n  query MasterData {\n    colors { id name slug }\n    bodyTypes { id name slug }\n    fuelTypes { id name slug }\n    transmissions { id name slug }\n    categories { id name slug icon sortOrder isActive }\n  }\n": typeof types.MasterDataDocument,
    "\n  query Trending($limit: Int) {\n    trending(limit: $limit) {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      condition\n      brand { id name slug }\n      model { id name slug }\n      transmission\n      fuelType\n      seller { id name avatar isVerified rating totalReviews }\n      viewCount\n    }\n  }\n": typeof types.TrendingDocument,
    "\n  query Favorites {\n    favorites {\n      id\n      listingId\n      userId\n      listing {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        condition\n        brand { id name slug }\n        model { id name slug }\n      }\n      createdAt\n    }\n  }\n": typeof types.FavoritesDocument,
    "\n  query Recommendations {\n    recommendations {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      condition\n      brand { id name slug }\n      model { id name slug }\n      transmission\n      fuelType\n      seller { id name avatar isVerified rating totalReviews }\n      viewCount\n    }\n  }\n": typeof types.RecommendationsDocument,
    "\n  query ListingReviews($listingId: ID!) {\n    listingReviews(listingId: $listingId) {\n      id\n      rating\n      comment\n      createdAt\n      user { id name avatar }\n    }\n  }\n": typeof types.ListingReviewsDocument,
    "\n  query Orders {\n    orders {\n      id\n      status\n      totalPrice\n      paymentStatus\n      paymentMethod\n      createdAt\n      updatedAt\n      listing {\n        id\n        slug\n        title\n        price\n        year\n        images\n        brand { id name slug }\n        model { id name slug }\n        condition\n      }\n    }\n  }\n": typeof types.OrdersDocument,
    "\n  query TokenPackages {\n    tokenPackages {\n      id\n      name\n      description\n      tokens\n      tokenAmount\n      price\n      bonus\n      bonusTokens\n      isPopular\n      features\n    }\n  }\n": typeof types.TokenPackagesDocument,
    "\n  query Dealers($page: Int, $perPage: Int) {\n    dealers(page: $page, perPage: $perPage) {\n      id\n      slug\n      name\n      logo\n      logoUrl\n      description\n      address\n      city\n      province\n      phone\n      email\n      rating\n      totalReviews\n      totalListings\n      isVerified\n      joinedAt\n    }\n  }\n": typeof types.DealersDocument,
    "\n  query DealerBySlug($slug: String!) {\n    dealerBySlug(slug: $slug) {\n      id\n      slug\n      name\n      logo\n      logoUrl\n      coverUrl\n      description\n      address\n      city\n      province\n      phone\n      email\n      website\n      rating\n      totalReviews\n      totalListings\n      branchCount\n      isVerified\n      createdAt\n      branches { id name address city province phone isPrimary lat lng }\n      listings {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        images\n        condition\n        brand { id name slug }\n        model { id name slug }\n        transmission\n        fuelType\n      }\n    }\n  }\n": typeof types.DealerBySlugDocument,
    "\n  query Banners($position: String) {\n    banners(position: $position) {\n      id\n      title\n      subtitle\n      image\n      imageUrl\n      link\n      linkUrl\n      position\n      sortOrder\n      isActive\n    }\n  }\n": typeof types.BannersDocument,
    "\n  query Conversations {\n    conversations {\n      id\n      listingId\n      buyerId\n      sellerId\n      lastMessage { id content createdAt sender { id name } }\n      lastMessageAt\n      unreadCount\n      status\n      createdAt\n      updatedAt\n      listing { id slug title price images }\n      participants { id name avatar isOnline }\n    }\n  }\n": typeof types.ConversationsDocument,
    "\n  query ConversationDetail($id: ID!) {\n    conversation(id: $id) {\n      id\n      listingId\n      buyerId\n      sellerId\n      lastMessage { id content createdAt sender { id name } }\n      lastMessageAt\n      unreadCount\n      status\n      createdAt\n      updatedAt\n      listing { id slug title price images seller { id name avatar } }\n      participants { id name avatar isOnline lastSeen }\n      messages { id content sender { id name avatar } createdAt isRead }\n    }\n  }\n": typeof types.ConversationDetailDocument,
    "\n  query Messages($conversationId: ID!) {\n    messages(conversationId: $conversationId) {\n      id\n      content\n      sender { id name avatar }\n      createdAt\n      isRead\n    }\n  }\n": typeof types.MessagesDocument,
    "\n  query Notifications($unreadOnly: Boolean) {\n    notifications(unreadOnly: $unreadOnly) {\n      id\n      userId\n      type\n      title\n      body\n      message\n      data\n      isRead\n      createdAt\n    }\n  }\n": typeof types.NotificationsDocument,
    "\n  query UnreadNotificationCount {\n    unreadNotificationCount\n  }\n": typeof types.UnreadNotificationCountDocument,
    "\n  query SystemSettings($group: String) {\n    systemSettings(group: $group) {\n      id\n      key\n      value\n      type\n      group\n      description\n    }\n  }\n": typeof types.SystemSettingsDocument,
    "\n  query LandingData {\n    landingData {\n      categories {\n        id\n        name\n        slug\n        icon\n        listingCount\n      }\n      featured {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        isFeatured\n        condition\n        brand { id name slug logo }\n        model { id name slug }\n        transmission\n        fuelType\n        seller { id name avatar isVerified rating totalReviews }\n        viewCount\n      }\n      latest {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        isFeatured\n        condition\n        brand { id name slug }\n        model { id name slug }\n        transmission\n        fuelType\n        seller { id name avatar isVerified rating totalReviews }\n        viewCount\n      }\n      popular {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        isFeatured\n        condition\n        brand { id name slug }\n        model { id name slug }\n        transmission\n        fuelType\n        seller { id name avatar isVerified rating totalReviews }\n        viewCount\n      }\n    }\n  }\n": typeof types.LandingDataDocument,
    "\n  mutation GoogleLogin($token: String!) {\n    googleLogin(token: $token) {\n      token\n      user {\n        id\n        name\n        email\n        avatar\n        role\n        isVerified\n        tokenBalance\n      }\n    }\n  }\n": typeof types.GoogleLoginDocument,
    "\n  mutation UpdateProfile($input: UpdateProfileInput!) {\n    updateProfile(input: $input) {\n      id\n      name\n      email\n      phone\n      avatar\n      bio\n      address\n      city\n      province\n    }\n  }\n": typeof types.UpdateProfileDocument,
    "\n  mutation CreateListing($input: CreateListingInput!) {\n    createListing(input: $input) {\n      id\n      slug\n      title\n      status\n    }\n  }\n": typeof types.CreateListingDocument,
    "\n  mutation UpdateListing($id: ID!, $input: CreateListingInput!) {\n    updateListing(id: $id, input: $input) {\n      id\n      slug\n      title\n      status\n    }\n  }\n": typeof types.UpdateListingDocument,
    "\n  mutation DeleteListing($id: ID!) {\n    deleteListing(id: $id) {\n      success\n      message\n    }\n  }\n": typeof types.DeleteListingDocument,
    "\n  mutation ToggleFavorite($listingId: ID!) {\n    toggleFavorite(listingId: $listingId) {\n      isFavorited\n      favoriteCount\n    }\n  }\n": typeof types.ToggleFavoriteDocument,
    "\n  mutation CreateReview($input: CreateReviewInput!) {\n    createReview(input: $input) {\n      id\n      rating\n      comment\n      createdAt\n    }\n  }\n": typeof types.CreateReviewDocument,
    "\n  mutation CreateOrder($input: CreateOrderInput!) {\n    createOrder(input: $input) {\n      id\n      status\n      totalPrice\n      createdAt\n    }\n  }\n": typeof types.CreateOrderDocument,
    "\n  mutation CreateConversation($listingId: ID!) {\n    createConversation(listingId: $listingId) {\n      id\n      listing { id slug title price images }\n      participants { id name avatar }\n    }\n  }\n": typeof types.CreateConversationDocument,
    "\n  mutation SendMessage($conversationId: ID!, $content: String!) {\n    sendMessage(conversationId: $conversationId, content: $content) {\n      id\n      content\n      sender { id name avatar }\n      createdAt\n      isRead\n    }\n  }\n": typeof types.SendMessageDocument,
};
const documents: Documents = {
    "\n  query Health {\n    health\n  }\n": types.HealthDocument,
    "\n  query Me {\n    me {\n      id\n      name\n      email\n      phone\n      avatar\n      role\n      isVerified\n      settings { id userId key value }\n      tokenBalance\n    }\n  }\n": types.MeDocument,
    "\n  query Listings($page: Int, $perPage: Int, $filter: ListingFilter) {\n    listings(page: $page, perPage: $perPage, filter: $filter) {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      isFeatured\n      condition\n      brand { id name slug logo }\n      model { id name slug }\n      transmission\n      fuelType\n      color\n      bodyType\n      seller { id name avatar isVerified rating totalReviews }\n      viewCount\n      createdAt\n    }\n  }\n": types.ListingsDocument,
    "\n  query Listing($id: ID!) {\n    listing(id: $id) {\n      id\n      slug\n      title\n      description\n      price\n      year\n      mileage\n      city\n      province\n      images\n      isFeatured\n      isNegotiable\n      condition\n      brand { id name slug logo }\n      model { id name slug }\n      variant\n      transmission\n      fuelType\n      color\n      bodyType\n      engineCapacity\n      seatCapacity\n      features\n      category { id name slug }\n      inspection {\n        id\n        status\n        overallScore\n        inspectedAt\n        reportUrl\n        categories { id name score items { id name status notes } }\n      }\n      seller { id name avatar phone email isVerified rating totalReviews joinedAt totalListings address province city }\n      reviewCount\n      viewCount\n      favorites\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": types.ListingDocument,
    "\n  query ListingBySlug($slug: String!) {\n    listingBySlug(slug: $slug) {\n      id\n      slug\n      title\n      description\n      price\n      year\n      mileage\n      city\n      province\n      images\n      isFeatured\n      isNegotiable\n      condition\n      brand { id name slug logo }\n      model { id name slug }\n      variant\n      transmission\n      fuelType\n      color\n      bodyType\n      engineCapacity\n      seatCapacity\n      features\n      category { id name slug }\n      inspection {\n        id\n        status\n        overallScore\n        inspectedAt\n        reportUrl\n        categories { id name score items { id name status notes } }\n      }\n      seller { id name avatar phone email isVerified rating totalReviews joinedAt totalListings address province city }\n      reviewCount\n      viewCount\n      favorites\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": types.ListingBySlugDocument,
    "\n  query MyListings($page: Int, $perPage: Int) {\n    myListings(page: $page, perPage: $perPage) {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      status\n      viewCount\n      favorites\n      isFeatured\n      condition\n      brand { id name slug }\n      model { id name slug }\n      transmission\n      fuelType\n      createdAt\n    }\n  }\n": types.MyListingsDocument,
    "\n  query Brands {\n    brands {\n      id\n      name\n      slug\n      logo\n      logoUrl\n      country\n      models { id name slug }\n    }\n  }\n": types.BrandsDocument,
    "\n  query MasterData {\n    colors { id name slug }\n    bodyTypes { id name slug }\n    fuelTypes { id name slug }\n    transmissions { id name slug }\n    categories { id name slug icon sortOrder isActive }\n  }\n": types.MasterDataDocument,
    "\n  query Trending($limit: Int) {\n    trending(limit: $limit) {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      condition\n      brand { id name slug }\n      model { id name slug }\n      transmission\n      fuelType\n      seller { id name avatar isVerified rating totalReviews }\n      viewCount\n    }\n  }\n": types.TrendingDocument,
    "\n  query Favorites {\n    favorites {\n      id\n      listingId\n      userId\n      listing {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        condition\n        brand { id name slug }\n        model { id name slug }\n      }\n      createdAt\n    }\n  }\n": types.FavoritesDocument,
    "\n  query Recommendations {\n    recommendations {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      condition\n      brand { id name slug }\n      model { id name slug }\n      transmission\n      fuelType\n      seller { id name avatar isVerified rating totalReviews }\n      viewCount\n    }\n  }\n": types.RecommendationsDocument,
    "\n  query ListingReviews($listingId: ID!) {\n    listingReviews(listingId: $listingId) {\n      id\n      rating\n      comment\n      createdAt\n      user { id name avatar }\n    }\n  }\n": types.ListingReviewsDocument,
    "\n  query Orders {\n    orders {\n      id\n      status\n      totalPrice\n      paymentStatus\n      paymentMethod\n      createdAt\n      updatedAt\n      listing {\n        id\n        slug\n        title\n        price\n        year\n        images\n        brand { id name slug }\n        model { id name slug }\n        condition\n      }\n    }\n  }\n": types.OrdersDocument,
    "\n  query TokenPackages {\n    tokenPackages {\n      id\n      name\n      description\n      tokens\n      tokenAmount\n      price\n      bonus\n      bonusTokens\n      isPopular\n      features\n    }\n  }\n": types.TokenPackagesDocument,
    "\n  query Dealers($page: Int, $perPage: Int) {\n    dealers(page: $page, perPage: $perPage) {\n      id\n      slug\n      name\n      logo\n      logoUrl\n      description\n      address\n      city\n      province\n      phone\n      email\n      rating\n      totalReviews\n      totalListings\n      isVerified\n      joinedAt\n    }\n  }\n": types.DealersDocument,
    "\n  query DealerBySlug($slug: String!) {\n    dealerBySlug(slug: $slug) {\n      id\n      slug\n      name\n      logo\n      logoUrl\n      coverUrl\n      description\n      address\n      city\n      province\n      phone\n      email\n      website\n      rating\n      totalReviews\n      totalListings\n      branchCount\n      isVerified\n      createdAt\n      branches { id name address city province phone isPrimary lat lng }\n      listings {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        images\n        condition\n        brand { id name slug }\n        model { id name slug }\n        transmission\n        fuelType\n      }\n    }\n  }\n": types.DealerBySlugDocument,
    "\n  query Banners($position: String) {\n    banners(position: $position) {\n      id\n      title\n      subtitle\n      image\n      imageUrl\n      link\n      linkUrl\n      position\n      sortOrder\n      isActive\n    }\n  }\n": types.BannersDocument,
    "\n  query Conversations {\n    conversations {\n      id\n      listingId\n      buyerId\n      sellerId\n      lastMessage { id content createdAt sender { id name } }\n      lastMessageAt\n      unreadCount\n      status\n      createdAt\n      updatedAt\n      listing { id slug title price images }\n      participants { id name avatar isOnline }\n    }\n  }\n": types.ConversationsDocument,
    "\n  query ConversationDetail($id: ID!) {\n    conversation(id: $id) {\n      id\n      listingId\n      buyerId\n      sellerId\n      lastMessage { id content createdAt sender { id name } }\n      lastMessageAt\n      unreadCount\n      status\n      createdAt\n      updatedAt\n      listing { id slug title price images seller { id name avatar } }\n      participants { id name avatar isOnline lastSeen }\n      messages { id content sender { id name avatar } createdAt isRead }\n    }\n  }\n": types.ConversationDetailDocument,
    "\n  query Messages($conversationId: ID!) {\n    messages(conversationId: $conversationId) {\n      id\n      content\n      sender { id name avatar }\n      createdAt\n      isRead\n    }\n  }\n": types.MessagesDocument,
    "\n  query Notifications($unreadOnly: Boolean) {\n    notifications(unreadOnly: $unreadOnly) {\n      id\n      userId\n      type\n      title\n      body\n      message\n      data\n      isRead\n      createdAt\n    }\n  }\n": types.NotificationsDocument,
    "\n  query UnreadNotificationCount {\n    unreadNotificationCount\n  }\n": types.UnreadNotificationCountDocument,
    "\n  query SystemSettings($group: String) {\n    systemSettings(group: $group) {\n      id\n      key\n      value\n      type\n      group\n      description\n    }\n  }\n": types.SystemSettingsDocument,
    "\n  query LandingData {\n    landingData {\n      categories {\n        id\n        name\n        slug\n        icon\n        listingCount\n      }\n      featured {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        isFeatured\n        condition\n        brand { id name slug logo }\n        model { id name slug }\n        transmission\n        fuelType\n        seller { id name avatar isVerified rating totalReviews }\n        viewCount\n      }\n      latest {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        isFeatured\n        condition\n        brand { id name slug }\n        model { id name slug }\n        transmission\n        fuelType\n        seller { id name avatar isVerified rating totalReviews }\n        viewCount\n      }\n      popular {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        isFeatured\n        condition\n        brand { id name slug }\n        model { id name slug }\n        transmission\n        fuelType\n        seller { id name avatar isVerified rating totalReviews }\n        viewCount\n      }\n    }\n  }\n": types.LandingDataDocument,
    "\n  mutation GoogleLogin($token: String!) {\n    googleLogin(token: $token) {\n      token\n      user {\n        id\n        name\n        email\n        avatar\n        role\n        isVerified\n        tokenBalance\n      }\n    }\n  }\n": types.GoogleLoginDocument,
    "\n  mutation UpdateProfile($input: UpdateProfileInput!) {\n    updateProfile(input: $input) {\n      id\n      name\n      email\n      phone\n      avatar\n      bio\n      address\n      city\n      province\n    }\n  }\n": types.UpdateProfileDocument,
    "\n  mutation CreateListing($input: CreateListingInput!) {\n    createListing(input: $input) {\n      id\n      slug\n      title\n      status\n    }\n  }\n": types.CreateListingDocument,
    "\n  mutation UpdateListing($id: ID!, $input: CreateListingInput!) {\n    updateListing(id: $id, input: $input) {\n      id\n      slug\n      title\n      status\n    }\n  }\n": types.UpdateListingDocument,
    "\n  mutation DeleteListing($id: ID!) {\n    deleteListing(id: $id) {\n      success\n      message\n    }\n  }\n": types.DeleteListingDocument,
    "\n  mutation ToggleFavorite($listingId: ID!) {\n    toggleFavorite(listingId: $listingId) {\n      isFavorited\n      favoriteCount\n    }\n  }\n": types.ToggleFavoriteDocument,
    "\n  mutation CreateReview($input: CreateReviewInput!) {\n    createReview(input: $input) {\n      id\n      rating\n      comment\n      createdAt\n    }\n  }\n": types.CreateReviewDocument,
    "\n  mutation CreateOrder($input: CreateOrderInput!) {\n    createOrder(input: $input) {\n      id\n      status\n      totalPrice\n      createdAt\n    }\n  }\n": types.CreateOrderDocument,
    "\n  mutation CreateConversation($listingId: ID!) {\n    createConversation(listingId: $listingId) {\n      id\n      listing { id slug title price images }\n      participants { id name avatar }\n    }\n  }\n": types.CreateConversationDocument,
    "\n  mutation SendMessage($conversationId: ID!, $content: String!) {\n    sendMessage(conversationId: $conversationId, content: $content) {\n      id\n      content\n      sender { id name avatar }\n      createdAt\n      isRead\n    }\n  }\n": types.SendMessageDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Health {\n    health\n  }\n"): (typeof documents)["\n  query Health {\n    health\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Me {\n    me {\n      id\n      name\n      email\n      phone\n      avatar\n      role\n      isVerified\n      settings { id userId key value }\n      tokenBalance\n    }\n  }\n"): (typeof documents)["\n  query Me {\n    me {\n      id\n      name\n      email\n      phone\n      avatar\n      role\n      isVerified\n      settings { id userId key value }\n      tokenBalance\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Listings($page: Int, $perPage: Int, $filter: ListingFilter) {\n    listings(page: $page, perPage: $perPage, filter: $filter) {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      isFeatured\n      condition\n      brand { id name slug logo }\n      model { id name slug }\n      transmission\n      fuelType\n      color\n      bodyType\n      seller { id name avatar isVerified rating totalReviews }\n      viewCount\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query Listings($page: Int, $perPage: Int, $filter: ListingFilter) {\n    listings(page: $page, perPage: $perPage, filter: $filter) {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      isFeatured\n      condition\n      brand { id name slug logo }\n      model { id name slug }\n      transmission\n      fuelType\n      color\n      bodyType\n      seller { id name avatar isVerified rating totalReviews }\n      viewCount\n      createdAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Listing($id: ID!) {\n    listing(id: $id) {\n      id\n      slug\n      title\n      description\n      price\n      year\n      mileage\n      city\n      province\n      images\n      isFeatured\n      isNegotiable\n      condition\n      brand { id name slug logo }\n      model { id name slug }\n      variant\n      transmission\n      fuelType\n      color\n      bodyType\n      engineCapacity\n      seatCapacity\n      features\n      category { id name slug }\n      inspection {\n        id\n        status\n        overallScore\n        inspectedAt\n        reportUrl\n        categories { id name score items { id name status notes } }\n      }\n      seller { id name avatar phone email isVerified rating totalReviews joinedAt totalListings address province city }\n      reviewCount\n      viewCount\n      favorites\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query Listing($id: ID!) {\n    listing(id: $id) {\n      id\n      slug\n      title\n      description\n      price\n      year\n      mileage\n      city\n      province\n      images\n      isFeatured\n      isNegotiable\n      condition\n      brand { id name slug logo }\n      model { id name slug }\n      variant\n      transmission\n      fuelType\n      color\n      bodyType\n      engineCapacity\n      seatCapacity\n      features\n      category { id name slug }\n      inspection {\n        id\n        status\n        overallScore\n        inspectedAt\n        reportUrl\n        categories { id name score items { id name status notes } }\n      }\n      seller { id name avatar phone email isVerified rating totalReviews joinedAt totalListings address province city }\n      reviewCount\n      viewCount\n      favorites\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query ListingBySlug($slug: String!) {\n    listingBySlug(slug: $slug) {\n      id\n      slug\n      title\n      description\n      price\n      year\n      mileage\n      city\n      province\n      images\n      isFeatured\n      isNegotiable\n      condition\n      brand { id name slug logo }\n      model { id name slug }\n      variant\n      transmission\n      fuelType\n      color\n      bodyType\n      engineCapacity\n      seatCapacity\n      features\n      category { id name slug }\n      inspection {\n        id\n        status\n        overallScore\n        inspectedAt\n        reportUrl\n        categories { id name score items { id name status notes } }\n      }\n      seller { id name avatar phone email isVerified rating totalReviews joinedAt totalListings address province city }\n      reviewCount\n      viewCount\n      favorites\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query ListingBySlug($slug: String!) {\n    listingBySlug(slug: $slug) {\n      id\n      slug\n      title\n      description\n      price\n      year\n      mileage\n      city\n      province\n      images\n      isFeatured\n      isNegotiable\n      condition\n      brand { id name slug logo }\n      model { id name slug }\n      variant\n      transmission\n      fuelType\n      color\n      bodyType\n      engineCapacity\n      seatCapacity\n      features\n      category { id name slug }\n      inspection {\n        id\n        status\n        overallScore\n        inspectedAt\n        reportUrl\n        categories { id name score items { id name status notes } }\n      }\n      seller { id name avatar phone email isVerified rating totalReviews joinedAt totalListings address province city }\n      reviewCount\n      viewCount\n      favorites\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query MyListings($page: Int, $perPage: Int) {\n    myListings(page: $page, perPage: $perPage) {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      status\n      viewCount\n      favorites\n      isFeatured\n      condition\n      brand { id name slug }\n      model { id name slug }\n      transmission\n      fuelType\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query MyListings($page: Int, $perPage: Int) {\n    myListings(page: $page, perPage: $perPage) {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      status\n      viewCount\n      favorites\n      isFeatured\n      condition\n      brand { id name slug }\n      model { id name slug }\n      transmission\n      fuelType\n      createdAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Brands {\n    brands {\n      id\n      name\n      slug\n      logo\n      logoUrl\n      country\n      models { id name slug }\n    }\n  }\n"): (typeof documents)["\n  query Brands {\n    brands {\n      id\n      name\n      slug\n      logo\n      logoUrl\n      country\n      models { id name slug }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query MasterData {\n    colors { id name slug }\n    bodyTypes { id name slug }\n    fuelTypes { id name slug }\n    transmissions { id name slug }\n    categories { id name slug icon sortOrder isActive }\n  }\n"): (typeof documents)["\n  query MasterData {\n    colors { id name slug }\n    bodyTypes { id name slug }\n    fuelTypes { id name slug }\n    transmissions { id name slug }\n    categories { id name slug icon sortOrder isActive }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Trending($limit: Int) {\n    trending(limit: $limit) {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      condition\n      brand { id name slug }\n      model { id name slug }\n      transmission\n      fuelType\n      seller { id name avatar isVerified rating totalReviews }\n      viewCount\n    }\n  }\n"): (typeof documents)["\n  query Trending($limit: Int) {\n    trending(limit: $limit) {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      condition\n      brand { id name slug }\n      model { id name slug }\n      transmission\n      fuelType\n      seller { id name avatar isVerified rating totalReviews }\n      viewCount\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Favorites {\n    favorites {\n      id\n      listingId\n      userId\n      listing {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        condition\n        brand { id name slug }\n        model { id name slug }\n      }\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query Favorites {\n    favorites {\n      id\n      listingId\n      userId\n      listing {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        condition\n        brand { id name slug }\n        model { id name slug }\n      }\n      createdAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Recommendations {\n    recommendations {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      condition\n      brand { id name slug }\n      model { id name slug }\n      transmission\n      fuelType\n      seller { id name avatar isVerified rating totalReviews }\n      viewCount\n    }\n  }\n"): (typeof documents)["\n  query Recommendations {\n    recommendations {\n      id\n      slug\n      title\n      price\n      year\n      mileage\n      city\n      province\n      images\n      condition\n      brand { id name slug }\n      model { id name slug }\n      transmission\n      fuelType\n      seller { id name avatar isVerified rating totalReviews }\n      viewCount\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query ListingReviews($listingId: ID!) {\n    listingReviews(listingId: $listingId) {\n      id\n      rating\n      comment\n      createdAt\n      user { id name avatar }\n    }\n  }\n"): (typeof documents)["\n  query ListingReviews($listingId: ID!) {\n    listingReviews(listingId: $listingId) {\n      id\n      rating\n      comment\n      createdAt\n      user { id name avatar }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Orders {\n    orders {\n      id\n      status\n      totalPrice\n      paymentStatus\n      paymentMethod\n      createdAt\n      updatedAt\n      listing {\n        id\n        slug\n        title\n        price\n        year\n        images\n        brand { id name slug }\n        model { id name slug }\n        condition\n      }\n    }\n  }\n"): (typeof documents)["\n  query Orders {\n    orders {\n      id\n      status\n      totalPrice\n      paymentStatus\n      paymentMethod\n      createdAt\n      updatedAt\n      listing {\n        id\n        slug\n        title\n        price\n        year\n        images\n        brand { id name slug }\n        model { id name slug }\n        condition\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query TokenPackages {\n    tokenPackages {\n      id\n      name\n      description\n      tokens\n      tokenAmount\n      price\n      bonus\n      bonusTokens\n      isPopular\n      features\n    }\n  }\n"): (typeof documents)["\n  query TokenPackages {\n    tokenPackages {\n      id\n      name\n      description\n      tokens\n      tokenAmount\n      price\n      bonus\n      bonusTokens\n      isPopular\n      features\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Dealers($page: Int, $perPage: Int) {\n    dealers(page: $page, perPage: $perPage) {\n      id\n      slug\n      name\n      logo\n      logoUrl\n      description\n      address\n      city\n      province\n      phone\n      email\n      rating\n      totalReviews\n      totalListings\n      isVerified\n      joinedAt\n    }\n  }\n"): (typeof documents)["\n  query Dealers($page: Int, $perPage: Int) {\n    dealers(page: $page, perPage: $perPage) {\n      id\n      slug\n      name\n      logo\n      logoUrl\n      description\n      address\n      city\n      province\n      phone\n      email\n      rating\n      totalReviews\n      totalListings\n      isVerified\n      joinedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query DealerBySlug($slug: String!) {\n    dealerBySlug(slug: $slug) {\n      id\n      slug\n      name\n      logo\n      logoUrl\n      coverUrl\n      description\n      address\n      city\n      province\n      phone\n      email\n      website\n      rating\n      totalReviews\n      totalListings\n      branchCount\n      isVerified\n      createdAt\n      branches { id name address city province phone isPrimary lat lng }\n      listings {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        images\n        condition\n        brand { id name slug }\n        model { id name slug }\n        transmission\n        fuelType\n      }\n    }\n  }\n"): (typeof documents)["\n  query DealerBySlug($slug: String!) {\n    dealerBySlug(slug: $slug) {\n      id\n      slug\n      name\n      logo\n      logoUrl\n      coverUrl\n      description\n      address\n      city\n      province\n      phone\n      email\n      website\n      rating\n      totalReviews\n      totalListings\n      branchCount\n      isVerified\n      createdAt\n      branches { id name address city province phone isPrimary lat lng }\n      listings {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        images\n        condition\n        brand { id name slug }\n        model { id name slug }\n        transmission\n        fuelType\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Banners($position: String) {\n    banners(position: $position) {\n      id\n      title\n      subtitle\n      image\n      imageUrl\n      link\n      linkUrl\n      position\n      sortOrder\n      isActive\n    }\n  }\n"): (typeof documents)["\n  query Banners($position: String) {\n    banners(position: $position) {\n      id\n      title\n      subtitle\n      image\n      imageUrl\n      link\n      linkUrl\n      position\n      sortOrder\n      isActive\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Conversations {\n    conversations {\n      id\n      listingId\n      buyerId\n      sellerId\n      lastMessage { id content createdAt sender { id name } }\n      lastMessageAt\n      unreadCount\n      status\n      createdAt\n      updatedAt\n      listing { id slug title price images }\n      participants { id name avatar isOnline }\n    }\n  }\n"): (typeof documents)["\n  query Conversations {\n    conversations {\n      id\n      listingId\n      buyerId\n      sellerId\n      lastMessage { id content createdAt sender { id name } }\n      lastMessageAt\n      unreadCount\n      status\n      createdAt\n      updatedAt\n      listing { id slug title price images }\n      participants { id name avatar isOnline }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query ConversationDetail($id: ID!) {\n    conversation(id: $id) {\n      id\n      listingId\n      buyerId\n      sellerId\n      lastMessage { id content createdAt sender { id name } }\n      lastMessageAt\n      unreadCount\n      status\n      createdAt\n      updatedAt\n      listing { id slug title price images seller { id name avatar } }\n      participants { id name avatar isOnline lastSeen }\n      messages { id content sender { id name avatar } createdAt isRead }\n    }\n  }\n"): (typeof documents)["\n  query ConversationDetail($id: ID!) {\n    conversation(id: $id) {\n      id\n      listingId\n      buyerId\n      sellerId\n      lastMessage { id content createdAt sender { id name } }\n      lastMessageAt\n      unreadCount\n      status\n      createdAt\n      updatedAt\n      listing { id slug title price images seller { id name avatar } }\n      participants { id name avatar isOnline lastSeen }\n      messages { id content sender { id name avatar } createdAt isRead }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Messages($conversationId: ID!) {\n    messages(conversationId: $conversationId) {\n      id\n      content\n      sender { id name avatar }\n      createdAt\n      isRead\n    }\n  }\n"): (typeof documents)["\n  query Messages($conversationId: ID!) {\n    messages(conversationId: $conversationId) {\n      id\n      content\n      sender { id name avatar }\n      createdAt\n      isRead\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Notifications($unreadOnly: Boolean) {\n    notifications(unreadOnly: $unreadOnly) {\n      id\n      userId\n      type\n      title\n      body\n      message\n      data\n      isRead\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query Notifications($unreadOnly: Boolean) {\n    notifications(unreadOnly: $unreadOnly) {\n      id\n      userId\n      type\n      title\n      body\n      message\n      data\n      isRead\n      createdAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query UnreadNotificationCount {\n    unreadNotificationCount\n  }\n"): (typeof documents)["\n  query UnreadNotificationCount {\n    unreadNotificationCount\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query SystemSettings($group: String) {\n    systemSettings(group: $group) {\n      id\n      key\n      value\n      type\n      group\n      description\n    }\n  }\n"): (typeof documents)["\n  query SystemSettings($group: String) {\n    systemSettings(group: $group) {\n      id\n      key\n      value\n      type\n      group\n      description\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query LandingData {\n    landingData {\n      categories {\n        id\n        name\n        slug\n        icon\n        listingCount\n      }\n      featured {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        isFeatured\n        condition\n        brand { id name slug logo }\n        model { id name slug }\n        transmission\n        fuelType\n        seller { id name avatar isVerified rating totalReviews }\n        viewCount\n      }\n      latest {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        isFeatured\n        condition\n        brand { id name slug }\n        model { id name slug }\n        transmission\n        fuelType\n        seller { id name avatar isVerified rating totalReviews }\n        viewCount\n      }\n      popular {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        isFeatured\n        condition\n        brand { id name slug }\n        model { id name slug }\n        transmission\n        fuelType\n        seller { id name avatar isVerified rating totalReviews }\n        viewCount\n      }\n    }\n  }\n"): (typeof documents)["\n  query LandingData {\n    landingData {\n      categories {\n        id\n        name\n        slug\n        icon\n        listingCount\n      }\n      featured {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        isFeatured\n        condition\n        brand { id name slug logo }\n        model { id name slug }\n        transmission\n        fuelType\n        seller { id name avatar isVerified rating totalReviews }\n        viewCount\n      }\n      latest {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        isFeatured\n        condition\n        brand { id name slug }\n        model { id name slug }\n        transmission\n        fuelType\n        seller { id name avatar isVerified rating totalReviews }\n        viewCount\n      }\n      popular {\n        id\n        slug\n        title\n        price\n        year\n        mileage\n        city\n        province\n        images\n        isFeatured\n        condition\n        brand { id name slug }\n        model { id name slug }\n        transmission\n        fuelType\n        seller { id name avatar isVerified rating totalReviews }\n        viewCount\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation GoogleLogin($token: String!) {\n    googleLogin(token: $token) {\n      token\n      user {\n        id\n        name\n        email\n        avatar\n        role\n        isVerified\n        tokenBalance\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation GoogleLogin($token: String!) {\n    googleLogin(token: $token) {\n      token\n      user {\n        id\n        name\n        email\n        avatar\n        role\n        isVerified\n        tokenBalance\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateProfile($input: UpdateProfileInput!) {\n    updateProfile(input: $input) {\n      id\n      name\n      email\n      phone\n      avatar\n      bio\n      address\n      city\n      province\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateProfile($input: UpdateProfileInput!) {\n    updateProfile(input: $input) {\n      id\n      name\n      email\n      phone\n      avatar\n      bio\n      address\n      city\n      province\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateListing($input: CreateListingInput!) {\n    createListing(input: $input) {\n      id\n      slug\n      title\n      status\n    }\n  }\n"): (typeof documents)["\n  mutation CreateListing($input: CreateListingInput!) {\n    createListing(input: $input) {\n      id\n      slug\n      title\n      status\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateListing($id: ID!, $input: CreateListingInput!) {\n    updateListing(id: $id, input: $input) {\n      id\n      slug\n      title\n      status\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateListing($id: ID!, $input: CreateListingInput!) {\n    updateListing(id: $id, input: $input) {\n      id\n      slug\n      title\n      status\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteListing($id: ID!) {\n    deleteListing(id: $id) {\n      success\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteListing($id: ID!) {\n    deleteListing(id: $id) {\n      success\n      message\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation ToggleFavorite($listingId: ID!) {\n    toggleFavorite(listingId: $listingId) {\n      isFavorited\n      favoriteCount\n    }\n  }\n"): (typeof documents)["\n  mutation ToggleFavorite($listingId: ID!) {\n    toggleFavorite(listingId: $listingId) {\n      isFavorited\n      favoriteCount\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateReview($input: CreateReviewInput!) {\n    createReview(input: $input) {\n      id\n      rating\n      comment\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreateReview($input: CreateReviewInput!) {\n    createReview(input: $input) {\n      id\n      rating\n      comment\n      createdAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateOrder($input: CreateOrderInput!) {\n    createOrder(input: $input) {\n      id\n      status\n      totalPrice\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreateOrder($input: CreateOrderInput!) {\n    createOrder(input: $input) {\n      id\n      status\n      totalPrice\n      createdAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateConversation($listingId: ID!) {\n    createConversation(listingId: $listingId) {\n      id\n      listing { id slug title price images }\n      participants { id name avatar }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateConversation($listingId: ID!) {\n    createConversation(listingId: $listingId) {\n      id\n      listing { id slug title price images }\n      participants { id name avatar }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation SendMessage($conversationId: ID!, $content: String!) {\n    sendMessage(conversationId: $conversationId, content: $content) {\n      id\n      content\n      sender { id name avatar }\n      createdAt\n      isRead\n    }\n  }\n"): (typeof documents)["\n  mutation SendMessage($conversationId: ID!, $content: String!) {\n    sendMessage(conversationId: $conversationId, content: $content) {\n      id\n      content\n      sender { id name avatar }\n      createdAt\n      isRead\n    }\n  }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;